export const categoryList = [
  "Plumbing",
  "Electrical",
  "Carpentry",
  "Home Services",
  "Cleaning",
  "Painting",
  "HVAC",
  "Air Conditioning",
  "Appliance Repair",
  "Roofing",
  "Flooring",
  "Tiling",
  "Gardening",
  "Landscaping",
  "Pest Control",
  "Moving",
  "Handyman",
  "Security Systems",
  "IT & Computer Repair",
  "Mobile Repair",
  "Web Development",
  "Graphic Design",
  "Photography",
  "Videography",
  "Beauty & Personal Care",
  "Hair & Makeup",
  "Fitness & Personal Training",
  "Tutoring",
  "Education",
  "Translation",
  "Legal Services",
  "Accounting & Tax",
  "Insurance",
  "Real Estate",
  "Automotive",
  "Car Wash & Detailing",
  "Car Repair",
  "Motorcycle Repair",
  "Transport & Delivery",
  "Event Planning",
  "Catering",
  "Furniture Assembly",
  "Tailoring & Alterations",
  "Printing",
  "Metalwork & Welding",
  "Masonry & Concrete",
  "Water Tank Services",
  "Water & Sanitation",
  "Waste Removal",
  "Solar & Renewable Energy",
  "Satellite & TV",
  "Internet & Networking",
  "Electrical Appliances Install",
  "Childcare & Nanny",
  "Elderly Care",
  "Pet Services",
  "Agriculture Services",
  "Boat & Marine",
  "Locksmith",
  "Glass & Aluminum",
  "Interior Design",
  "Architecture & Engineering",
  "Digital Marketing",
  "Social Media Marketing",
  "SEO",
  "SEM & Paid Ads",
  "Content Marketing",
  "Copywriting",
  "Branding",
  "Advertising",
  "Influencer Marketing",
  "Email Marketing",
  "SMS Marketing",
  "Affiliate Marketing",
  "PR & Communications",
  "Market Research",
  "Retail & Store Fit-out",
  "Visual Merchandising",
  "Point of Sale (POS) Setup",
  "Storefront Signage",
  "Shop Interior Design",
  "Inventory Setup",
  "E-commerce Setup",
  "Marketplace Listings",
  "Packaging & Label Design",
  "Sales",
] as const;

export function formatCategoryLabel(value: string): string {
  const found = categoryList.find((c) => c === value);
  return found ? found : value;
}
